// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ..
// from ../gir-files
// DO NOT EDIT

glib::wrapper! {
    pub struct Color(BoxedInline<ffi::WebKitColor>);

    match fn {
        copy => |ptr| glib::gobject_ffi::g_boxed_copy(ffi::webkit_color_get_type(), ptr as *mut _) as *mut ffi::WebKitColor,
        free => |ptr| glib::gobject_ffi::g_boxed_free(ffi::webkit_color_get_type(), ptr as *mut _),
        type_ => || ffi::webkit_color_get_type(),
    }
}
