// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ..
// from ../gir-files
// DO NOT EDIT

use std::fmt;

glib::wrapper! {
    #[doc(alias = "WebKitDeviceInfoPermissionRequest")]
    pub struct DeviceInfoPermissionRequest(Object<ffi::WebKitDeviceInfoPermissionRequest, ffi::WebKitDeviceInfoPermissionRequestClass>);

    match fn {
        type_ => || ffi::webkit_device_info_permission_request_get_type(),
    }
}

impl DeviceInfoPermissionRequest {
        pub const NONE: Option<&'static DeviceInfoPermissionRequest> = None;
    
}

impl fmt::Display for DeviceInfoPermissionRequest {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("DeviceInfoPermissionRequest")
    }
}
