// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ..
// from ../gir-files
// DO NOT EDIT

use glib::object::IsA;
use glib::translate::*;
use std::fmt;
#[cfg(any(feature = "v2_20", feature = "dox"))]
#[cfg_attr(feature = "dox", doc(cfg(feature = "v2_20")))]
use std::ptr;

glib::wrapper! {
    #[doc(alias = "WebKitFormSubmissionRequest")]
    pub struct FormSubmissionRequest(Object<ffi::WebKitFormSubmissionRequest, ffi::WebKitFormSubmissionRequestClass>);

    match fn {
        type_ => || ffi::webkit_form_submission_request_get_type(),
    }
}

impl FormSubmissionRequest {
        pub const NONE: Option<&'static FormSubmissionRequest> = None;
    
}

pub trait FormSubmissionRequestExt: 'static {
    #[cfg(any(feature = "v2_20", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "v2_20")))]
    #[doc(alias = "webkit_form_submission_request_list_text_fields")]
    fn list_text_fields(&self) -> Option<(Vec<glib::GString>, Vec<glib::GString>)>;

    #[doc(alias = "webkit_form_submission_request_submit")]
    fn submit(&self);
}

impl<O: IsA<FormSubmissionRequest>> FormSubmissionRequestExt for O {
    #[cfg(any(feature = "v2_20", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "v2_20")))]
    fn list_text_fields(&self) -> Option<(Vec<glib::GString>, Vec<glib::GString>)> {
        unsafe {
            let mut field_names = ptr::null_mut();
            let mut field_values = ptr::null_mut();
            let ret = from_glib(ffi::webkit_form_submission_request_list_text_fields(self.as_ref().to_glib_none().0, &mut field_names, &mut field_values));
            if ret { Some((FromGlibPtrContainer::from_glib_none(field_names), FromGlibPtrContainer::from_glib_none(field_values))) } else { None }
        }
    }

    fn submit(&self) {
        unsafe {
            ffi::webkit_form_submission_request_submit(self.as_ref().to_glib_none().0);
        }
    }
}

impl fmt::Display for FormSubmissionRequest {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("FormSubmissionRequest")
    }
}
