// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ..
// from ../gir-files
// DO NOT EDIT

use std::fmt;

glib::wrapper! {
    #[doc(alias = "WebKitNotificationPermissionRequest")]
    pub struct NotificationPermissionRequest(Object<ffi::WebKitNotificationPermissionRequest, ffi::WebKitNotificationPermissionRequestClass>);

    match fn {
        type_ => || ffi::webkit_notification_permission_request_get_type(),
    }
}

impl NotificationPermissionRequest {
        pub const NONE: Option<&'static NotificationPermissionRequest> = None;
    
}

impl fmt::Display for NotificationPermissionRequest {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("NotificationPermissionRequest")
    }
}
