// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ..
// from ../gir-files
// DO NOT EDIT

use std::ffi::CStr;

#[cfg(any(feature = "v2_24", feature = "dox"))]
#[cfg_attr(feature = "dox", doc(cfg(feature = "v2_24")))]
#[doc(alias = "JSC_OPTIONS_USE_DFG")]
pub static OPTIONS_USE_DFG: once_cell::sync::Lazy<&'static str> = once_cell::sync::Lazy::new(|| unsafe{CStr::from_ptr(ffi::JSC_OPTIONS_USE_DFG).to_str().unwrap()});
#[cfg(any(feature = "v2_24", feature = "dox"))]
#[cfg_attr(feature = "dox", doc(cfg(feature = "v2_24")))]
#[doc(alias = "JSC_OPTIONS_USE_FTL")]
pub static OPTIONS_USE_FTL: once_cell::sync::Lazy<&'static str> = once_cell::sync::Lazy::new(|| unsafe{CStr::from_ptr(ffi::JSC_OPTIONS_USE_FTL).to_str().unwrap()});
#[cfg(any(feature = "v2_24", feature = "dox"))]
#[cfg_attr(feature = "dox", doc(cfg(feature = "v2_24")))]
#[doc(alias = "JSC_OPTIONS_USE_JIT")]
pub static OPTIONS_USE_JIT: once_cell::sync::Lazy<&'static str> = once_cell::sync::Lazy::new(|| unsafe{CStr::from_ptr(ffi::JSC_OPTIONS_USE_JIT).to_str().unwrap()});
#[cfg(any(feature = "v2_24", feature = "dox"))]
#[cfg_attr(feature = "dox", doc(cfg(feature = "v2_24")))]
#[doc(alias = "JSC_OPTIONS_USE_LLINT")]
pub static OPTIONS_USE_LLINT: once_cell::sync::Lazy<&'static str> = once_cell::sync::Lazy::new(|| unsafe{CStr::from_ptr(ffi::JSC_OPTIONS_USE_LLINT).to_str().unwrap()});
