[package]
name = "wpejavascriptcore"
version = "0.0.1"
edition = "2021"

[package.metadata.docs.rs]
features = ["dox"]

[lib]
name = "wpejavascriptcore"

[dependencies]
bitflags = "1.3.2"
glib = "0.15.11"

[dependencies.ffi]
package = "wpejavascriptcore-sys"
path = "../wpejavascriptcore-sys"
