[options]
library = "Soup"
version = "3.0"
target_path = "."
single_version_file = "."
min_cfg_version = "3.0"
work_mode = "sys"
girs_directories = [
    "../gir-files/",
    "../",
]

external_libraries = [
    "Gio",
    "GLib",
    "GObject",
]
